CREATE TABLE `messages` (
    `id` int NOT NULL AUTO_INCREMENT,
`name` varchar(1000) NOT NULL,
`contents` varchar(255) NOT NULL,
`created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(`id`))ENGINE=InnoDB  DEFAULT CHARSET=utf8